site_name: Гайды для маринов
site_url: https://shadugr.github.io/scmtwo-guide/
theme:
  name: material
  language: ru
  palette:
    # USCM Light Mode (Garrison/Uniform)
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue-grey
      accent: teal
      toggle:
        icon: material/weather-sunny
        name: Switch to Dark Mode
    # USCM Dark Mode (Tactical/Night Ops)
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: green
      toggle:
        icon: material/weather-night
        name: Switch to Light Mode
extra:
  generator: false
use_directory_urls: true
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/header_link.js

nav:
  - Главная: index.md
  - Руководство начинающих морпехов:
    - Как зайти на сервер: guides/server_enter.md
    - Создание персонажа и выбор роли: guides/lobby.md
    - Интерфейс и управление: guides/interface.md
    - Первые шаги: guides/awakening.md
  - Лор и структура: lore.md
  # - Механики:
  - FAQ: faq.md

plugins:
  - search
  - glightbox

markdown_extensions:
  - attr_list
  - admonition
  - pymdownx.details
  - pymdownx.superfences